---
name: Secrets Workflow
run-name: ¡Hello Secrets!

on:
  workflow_dispatch:

jobs:
  Secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Show vars and secrets
        run: echo "Hi ${{ vars.USER }}, ${{ secrets.PASSWORD }}"
