---
name: Hello Triggers Workflow
run-name: ¡Hello Triggers!

on:
  push:
    branches:
      - main
      - aprendiendo-github-actions
  pull_request:
    branches:
      - main
      - aprendiendo-github-actions
  issues:
    types:
      - labeled
  schedule:
    - cron: '30,32,34,38,40,42,44,46,48,50 15 * * *'
  workflow_dispatch:

jobs:
  hello-triggers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        users:  actions/checkout

      - name: Variables
        run: echo "USERNAME=${{ github.actor }}" | tee -a $GITHUB_ENV

      - name: String
        run: perl hello_trigger.pl
