---
name: Hello Triggers Workflow
run-name: ¡Hello Triggers!

on:
  push:
    branches:
      - main
      - aprendiendo-github-actions
    paths:
      - hello_trigger.pl
  pull_request:
    branches:
      - main
    types:
      - closed
  issues:
    types:
      - labeled
  schedule:
    - cron: '0/10 20-23 * * *'
  workflow_dispatch:

jobs:
  hello-triggers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Variables
        run: |
          id
          pwd
          date
          hostname
          echo $GITHUB_ENV
          echo "USERNAME=${{ github.actor }}" | tee -a $GITHUB_ENV
          ls

      - name: String
        run: perl hello_trigger.pl
